substitutions:
  _REGION: "us-central1"                # change if needed
  _REPO: "AI_Analytics"                     # Artifact Registry repo name
  _SERVICE: "analytics-endpoints"               # Cloud Run service name
  _CPU: "1"
  _MEMORY: "512Mi"
  _MIN_INSTANCES: "0"
  _MAX_INSTANCES: "50"
  _CONCURRENCY: "80"
  _ENV: "prod"
  _ALLOW_UNAUTH: "true"                 # "true" to make the API public

timeout: "1200s"

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8"

steps:
# (optional) print variables for sanity
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: bash
  args:
    - -lc
    - |
      echo "PROJECT_ID=$PROJECT_ID"
      echo "SHORT_SHA=$SHORT_SHA"
      echo "_REGION=${_REGION}"
      echo "_REPO=${_REPO}"
      echo "_SERVICE=${_SERVICE}"

# 1) Build image from backend/Dockerfile
- name: gcr.io/cloud-builders/docker
  id: Build image
  args:
    [
      "build",
      "-f","backend/Dockerfile",
      "-t","${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/backend:${SHORT_SHA}",
      "backend"
    ]

# 2) Push image
- name: gcr.io/cloud-builders/docker
  id: Push image
  args:
    [ "push", "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/backend:${SHORT_SHA}" ]

# 3) Deploy to Cloud Run (with secrets + env vars)
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  id: Deploy to Cloud Run
  entrypoint: bash
  args:
    - -lc
    - |
      set -euo pipefail
      CMD=( gcloud run deploy "${_SERVICE}" \
        --image="${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/backend:${SHORT_SHA}" \
        --region="${_REGION}" \
        --port=8080 \
        --cpu="${_CPU}" \
        --memory="${_MEMORY}" \
        --min-instances="${_MIN_INSTANCES}" \
        --max-instances="${_MAX_INSTANCES}" \
        --concurrency="${_CONCURRENCY}" \
        --set-env-vars=ENV=${_ENV} \
        --set-secrets=MONGO_URI=MONGO_URI:latest,OPENAI_API_KEY=OPENAI_API_KEY:latest )
      if [[ "${_ALLOW_UNAUTH}" == "true" ]]; then
        CMD+=( --allow-unauthenticated )
      fi
      "${CMD[@]}"

images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/backend:${SHORT_SHA}"
